

import { Language, GeneralAppSettings, TestSpecificSettings, LanguagePack, AnswerNumberingStyle, MappedAppField } from './types.ts';

export const LOCAL_STORAGE_TEST_PROFILES_KEY = 'maciesLvTestProfiles_v1_react';
export const LOCAL_STORAGE_GENERAL_SETTINGS_KEY = 'maciesLvGeneralSettings_v1_react';
export const LOCAL_STORAGE_FLASHCARD_DECKS_KEY = 'maciesLvFlashcardDecks_v1_react';
export const LOCAL_STORAGE_ARTICLES_KEY = 'maciesLvArticles_v1_react';
export const LOCAL_STORAGE_ARTICLE_PROGRESS_KEY = 'maciesLvArticleProgress_v1_react';


export const MAX_FORM_OPTIONS = 6;
export const MAX_PREVIEW_ROWS = 5;
export const MAX_XLSX_IMPORT_ERRORS_TO_SHOW = 5;
export const MAX_IMAGE_SIZE_KB = 250;

// Wordle specific constants
export const WORDLE_MAX_ATTEMPTS = 6;


// Default Settings
export const DEFAULT_GENERAL_APP_SETTINGS: GeneralAppSettings = {
  currentLanguage: Language.LV,
  darkMode: true,
};

export const DEFAULT_TEST_SPECIFIC_SETTINGS: TestSpecificSettings = {
  numQuestions: 10,
  useAllQuestions: true,
  randomizeQuestions: true,
  randomizeAnswers: true,
  answerNumberingStyle: AnswerNumberingStyle.NUMBERS,
  enableTimer: false,
  timerDurationMinutes: 30,
};

export const APP_FIELDS_FOR_MAPPING: MappedAppField[] = [
    { key: 'question', labelKey: 'formQuestionTextLabel', required: true, group: 'main' },
    { key: 'type', labelKey: 'formQuestionTypeLabel', required: false, group: 'main', tipKey: 'qBankMappingTypeTip' },
    { key: 'topic', labelKey: 'formTopicLabel', required: false, group: 'main' },
    { key: 'correctOptionText', labelKey: 'formCorrectAnswerLabel', required: false, group: 'main', tipKey: 'qBankMappingCorrectAnswerTip' },
    { key: 'option1', labelKey: 'formOptionLabel', labelArgs: { number: 1 }, required: false, group: 'options' },
    { key: 'option2', labelKey: 'formOptionLabel', labelArgs: { number: 2 }, required: false, group: 'options' },
    { key: 'option3', labelKey: 'formOptionLabel', labelArgs: { number: 3 }, required: false, group: 'options' },
    { key: 'option4', labelKey: 'formOptionLabel', labelArgs: { number: 4 }, required: false, group: 'options' },
    { key: 'option5', labelKey: 'formOptionLabel', labelArgs: { number: 5 }, required: false, group: 'options' },
    { key: 'option6', labelKey: 'formOptionLabel', labelArgs: { number: 6 }, required: false, group: 'options' },
];


export const translations: LanguagePack = {
  [Language.LV]: {
    appTitle: "Mācies.lv",
    navHome: "Sākums",
    navMyTests: "Mani Testi",
    navQuestionBank: "Jautājumu Banka",
    navCreateQuestion: "Izveidot Jautājumu",
    navSettingsGeneral: "Vispārīgie Iestatījumi",
    navSettingsTest: "Testa Iestatījumi",
    navStats: "Statistika",
    navImportExport: "Importēt/Eksportēt",
    navImportXlsxCsv: "Importēt (XLSX/CSV)",

    // Home page
    homeWelcome: "Laipni lūgti Mācies.lv!",
    homeModulesTitle: "Pieejamie Moduļi",
    homeInteractiveTestsTitle: "Interaktīvie Testi",
    homeInteractiveTestsDesc: "Izveidojiet un kārtojiet pielāgotus testus, lai pārbaudītu savas zināšanas dažādās jomās.",
    homeFlashcardsTitle: "Zibatmiņas Kartītes",
    homeFlashcardsDesc: "Veidojiet un mācieties ar kartītēm. Lieliski piemērots jaunu vārdu un faktu apguvei.",
    homeGamesTitle: "Spēles",
    homeGamesDesc: "Izklaidējies un mācies ar interaktīvām spēlēm.",
    homeArticlesTitle: "Izglītojoši Raksti",
    homeArticlesDesc: "Lasiet rakstus par dažādām tēmām, lai paplašinātu savas zināšanas.",
    homeComingSoon: "Drīzumā!",
    
    // My Tests View
    myTestsTitle: "Mani Sagatavotie Testi",
    myTestsCreateNew: "Izveidot Jaunu Testu",
    myTestsNoProfiles: "Vēl nav izveidots neviens tests. Sāciet, izveidojot jaunu!",
    myTestsProfileNameLabel: "Testa nosaukums",
    myTestsProfileDescLabel: "Apraksts (nav obligāts)",
    myTestsProfileQuestions: "Jautājumi:",
    myTestsProfileCreated: "Izveidots:",
    myTestsProfileUpdated: "Atjaunināts:",
    myTestsOpenHub: "Atvērt Centru",
    myTestsEditDetails: "Rediģēt Detaļas",
    myTestsDelete: "Dzēst Testu",

    // Test Profile Hub View
    testProfileHubTitle: "Testa Centrs: {name}",
    testHubStartTest: "Sākt Testu",
    testHubManageBank: "Pārvaldīt Jautājumus",
    testHubAddQuestion: "Pievienot Jaunu Jautājumu",
    testHubViewStats: "Skatīt Statistiku",
    testHubConfigure: "Konfigurēt Šo Testu",
    testHubBackToAllTests: "Atpakaļ pie Visiem Testiem",
    navBackToHub: "Atpakaļ uz Centru",

    // Quiz View
    quizNoQuestionsAvailable: "Testam '{name}' nav pieejami jautājumi.",
    quizNoQuestionsAdvice: "Lūdzu, pievienojiet dažus jautājumus jautājumu bankā vai pārbaudiet testa iestatījumus.",
    quizQuestionOf: "{current} no {total}",
    quizResultsTitle: "Rezultāti",
    quizYourScore: "Jūsu rezultāts: {score} no {totalPossible} ({percentage}%)",
    quizCorrectAnswerWas: "Pareizā atbilde: {correctAnswer}",
    quizYourAnswerWas: "Jūsu atbilde: {userAnswer}. Pareizā: {correctAnswer}",
    quizAnswerNotAnswered: "Jūs neatbildējāt. Pareizā atbilde: {correctAnswer}",
    quizPreviousBtn: "Iepriekšējais",
    quizNextBtn: "Nākamais",
    quizSubmitBtn: "Iesniegt",
    quizTryAgainBtn: "Mēģināt Vēlreiz",
    quizGoToAddFromEmpty: "Pievienot Jautājumus",
    quizGoToSettingsFromEmpty: "Testa Iestatījumi",
    quizTimeRemaining: "Atlicis laiks: {time}",
    quizTimeUpTitle: "Laiks Beidzies!",
    quizTimeUpMessage: "Jūsu tests tika automātiski iesniegts, jo laiks ir beidzies.",

    // Question Bank View
    qBankTitle: "Jautājumu Banka: {name}",
    qBankSearchByText: "Meklēt pēc teksta",
    qBankSearchPlaceholder: "Ievadiet atslēgvārdu...",
    qBankFilterByTopic: "Filtrēt pēc tēmas",
    qBankAllTopics: "Visas tēmas",
    qBankTotalItems: "Kopā atrasti: {count}",
    qBankSelectAll: "Atlasīt Visus Redzamos",
    qBankDeleteSelected: "Dzēst Atlasītos",
    qBankItemsSelected: "Atlasīti: {count}",
    qBankTypeLabel: "Tips:",
    qBankAnswersCount: "Atbildes:",
    qBankCorrectIs: "Pareizā:",
    qBankEditBtn: "Rediģēt",
    qBankDeleteBtn: "Dzēst",
    qBankNoQuestions: "Šajā testā ('{name}') nav jautājumu. Pievienojiet dažus!",
    qBankBackToQuestionBank: "Atpakaļ uz Jautājumu Banku",
    qBankQuestionImageIndicator: "Jaut. attēls",
    qBankOptionImageIndicator: "Atb. attēls",
    qBankIdIs: "ID:",
    qBankNotSpecified: "Nav norādīts",
    qBankMappingTypeTip: "'multiple-choice', 'true-false', vai 'fill-in-the-blank'. Ja nav norādīts, būs 'multiple-choice'.",
    qBankMappingCorrectAnswerTip: "Piem., 'A', 'True', vai 'Rīga'. True/False var būt arī 'paties'/'aplams'.",

    // Create/Edit Question View
    formTitleAdd: "Pievienot Jaunu Jautājumu",
    formTitleEdit: "Rediģēt Jautājumu",
    formQuestionTypeLabel: "Jautājuma tips",
    formQuestionTextLabel: "Jautājuma teksts",
    formTopicLabel: "Tēma (nav obligāta)",
    formTopicPlaceholder: "Piem., Vēsture, Matemātika",
    formQuestionImageLabel: "Jautājuma attēls (neobligāts, līdz {maxSize}KB)",
    formOptionsLabel: "Atbilžu varianti",
    optionVariant: "Variants",
    formAddOptionBtn: "Pievienot variantu",
    formCorrectOptionLabel: "Pareizais variants",
    formCorrectAnswerLabel: "Pareizā atbilde",
    formFillCorrectAnswerPlaceholder: "Ievadiet pareizo atbildi",
    formCancelBtn: "Atcelt",
    formSaveQuestionBtn: "Saglabāt Jautājumu",
    formSaveChangesBtn: "Saglabāt Izmaiņas",
    formStatusSaving: "Saglabā...",
    formStatusSaved: "Jautājums saglabāts!",
    formStatusChangesSaved: "Izmaiņas saglabātas!",
    optionImageLabel: "Varianta attēls (neobligāts)",
    optionEmptyOrImage: "(tukšs vai tikai attēls)",
    formImageWarning: "Attēli tiek saglabāti pārlūkprogrammā. Lielāki attēli (virs {maxSize}KB) var palēnināt darbību vai netikt saglabāti.",

    // Question Types
    qTypeMultipleChoice: "Vairākatbilžu",
    qTypeTrueFalse: "Patiess/Aplams",
    qTypeFillInBlank: "Aizpildīt Tukšumu",

    // Options (True/False)
    optionTrue: "Patiess",
    optionFalse: "Aplams",

    // Stats View
    statsTitle: "Statistika: {name}",
    statsTotalTests: "Kopā Testi",
    statsAverageScore: "Vidējais Rezultāts",
    statsBestScore: "Labākais Rezultāts",
    statsHistoryTitle: "Vēsture",
    statsClearHistoryBtn: "Notīrīt Vēsturi",
    statsClearHistoryConfirm: "Vai tiešām vēlaties dzēst visu '{name}' testa vēsturi?",
    statsClearHistoryConfirmDetail: "Šo darbību nevarēs atsaukt.",
    statsHistoryCleared: "Vēsture Notīrīta",
    statsHistoryClearedDetail: "Testa '{name}' vēsture ir veiksmīgi notīrīta.",
    statsNoHistory: "Nav vēstures ierakstu testam '{name}'.",
    statsTestOn: "Tests veikts:",
    statsScore: "Rezultāts:",
    statsTimeTaken: "Patērētais laiks:",

    // Settings View (Test Specific)
    testSettingsTitle: "Konfigurācija: {name}",
    settingsAnswerNumbering: "Atbilžu numerācijas stils:",
    settingsNumQuestions: "Jautājumu skaits testā:",
    settingsAllQuestions: "Visi",
    settingsRandomQuestions: "Jaukt jautājumus",
    settingsRandomAnswers: "Jaukt atbildes",
    settingsSaveBtn: "Saglabāt Iestatījumus",
    settingsEnableTimer: "Iespējot taimeri",
    settingsTimerDurationMinutes: "Taimera ilgums (minūtēs):",

    // Settings View (General)
    generalSettingsTitle: "Vispārīgie Iestatījumi",
    settingsLanguageTitle: "Valoda",
    settingsDarkMode: "Tumšais režīms",
    settingsDataManagement: "Datu Pārvaldība",
    settingsClearDataBtn: "Dzēst Visus Datus",
    settingsClearDataWarning: "UZMANĪBU: Šī darbība neatgriezeniski dzēsīs VISUS jūsu saglabātos testus, jautājumus, vēsturi un iestatījumus. Vai esat pārliecināts?",
    
    // Modals & Messages
    modalOK: "Labi",
    modalCancel: "Atcelt",
    modalConfirm: "Apstiprināt",
    modalNotificationTitle: "Paziņojums",
    modalErrorTitle: "Kļūda",
    modalMappingTitle: "Datu Kartēšana Importam",
    modalMappingDescription: "Lūdzu, norādiet, kuri jūsu faila stabiņi atbilst lietotnes jautājumu laukiem. Neobligātos laukus varat atstāt tukšus.",
    mapDetectedHeaders: "Failā Atklātie Stabiņi:",
    mapToFieldLabel: "Kartēt uz Lietotnes Lauku '{fieldName}'",
    mapDoNotImport: "-- Neimportēt --",
    mapPreviewData: "Pirmās {count} rindas no jūsu faila:",
    btnStartImport: "Sākt Importu",

    msgValidationError: "Validācijas Kļūda",
    msgErrorQuestionTextMissing: "Jautājuma teksts ir obligāts.",
    msgNeedAtLeastTwoOptions: "Vairākatbilžu jautājumam nepieciešami vismaz 2 varianti.",
    msgChooseCorrectAnswer: "Lūdzu, izvēlieties pareizo atbildi.",
    msgMustEnterFillInAnswer: "Lūdzu, ievadiet pareizo atbildi tukšajā laukā.",
    msgErrorCorrectAnswerMismatchMcq: "Norādītā pareizā atbilde ('{correctAnswer}') neatbilst nevienam no ievadītajiem variantiem: {optionList}.",
    msgErrorInvalidCorrectAnswerTf: "Patiess/Aplams jautājuma pareizajai atbildei jābūt '{trueText}' vai '{falseText}'. Jūs norādījāt: '{providedAnswer}'.",
    msgErrorCorrectAnswerMissingMcq: "Lūdzu, norādiet pareizo atbildi vairākatbilžu jautājumam.",
    msgErrorCorrectAnswerMissingFib: "Lūdzu, norādiet pareizo atbildi aizpildāmajam jautājumam.",
    msgOptionIsImageOnlyCorrect: "Variants, kas satur tikai attēlu, nevar būt pareizā atbilde, ja tam nav teksta.",

    msgFileTooLarge: "Fails Pārāk Liels",
    msgFileTooLargeDetail: "Maksimālais atļautais faila izmērs ir {maxSize}KB. Jūsu fails: {fileSize}KB.",
    msgMaxOptionsReached: "Sasniegts Maksimālais Variantu Skaits",
    msgMaxOptionsDetail: "Jūs varat pievienot ne vairāk kā {max} atbilžu variantus.",
    
    msgImportConfirm: "Apstiprināt Importu",
    msgImportConfirmDetail: "Vai tiešām vēlaties importēt jautājumus no '{filename}' testam '{testName}'? Esošie jautājumi tiks aizstāti.",
    msgImportedSuccess: "Veiksmīgi Importēts",
    msgImportedSuccessDetail: "Jautājumi testam '{testName}' ir veiksmīgi importēti.",
    msgXlsxImportedSuccess: "{count} jautājumi no '{filename}' veiksmīgi importēti testam '{testName}'.",
    msgImportError: "Importēšanas Kļūda",
    msgImportErrorInvalidFormat: "Nederīgs faila formāts vai struktūra.",
    msgImportErrorReadFile: "Neizdevās nolasīt failu. Kļūda: {errorMessage}",
    msgImportErrorReadingFile: "Neizdevās nolasīt failu.",
    msgXlsxImportErrorNoSheet: "XLSX failā netika atrasta neviena lapa.",
    msgXlsxImportErrorNoHeaders: "Izvēlētajā lapā netika atrasti stabiņu nosaukumi (headeri).",
    msgXlsxImportErrorMapping: "Lai importētu, jautājuma teksts ('Jautājuma teksts') ir obligāti jānorāda kartēšanā.",
    msgXlsxImportNoValidQuestionsFound: "Failā netika atrasts neviens derīgs jautājums vai arī visi saturēja kļūdas.",
    msgXlsxImportCompletedWithRowErrorsTitle: "Imports Pabeigts ar Kļūdām Rindās",
    msgXlsxImportCompletedWithRowErrorsDetail: "Dažas rindas nevarēja importēt. Kopā {errorCount} kļūdainas rindas. Parādītas pirmās {shownErrorCount}:\n{errorListString}",
    msgXlsxImportRowErrorPrefix: "Rinda {rowNum}",
    msgErrorUnexpectedRowProcessing: "Neparedzēta kļūda rindas apstrādē: {errorMessage}",
    msgErrorMoreErrorsText: "papildu kļūdas...",


    msgExported: "Veiksmīgi Eksportēts",
    msgExportedDetail: "Jautājumi no testa '{testName}' saglabāti failā '{filename}'.",
    msgNoDataToExport: "Nav Datu Eksportam",
    msgNoDataToExportDetail: "Testā '{testName}' nav jautājumu, ko eksportēt.",
    
    msgSettingsSaved: "Iestatījumi Saglabāti",
    msgSettingsSavedDetail: "Izmaiņas ir veiksmīgi saglabātas.",
    msgSavingErrorDetail: "Kļūda saglabājot. Pārbaudiet datus un mēģiniet vēlreiz.",
    
    msgDataCleared: "Visi Dati Dzēsti",
    msgDataClearedDetail: "Visi jūsu dati ir veiksmīgi dzēsti no pārlūkprogrammas atmiņas.",
    msgClearAllDataConfirm: "Apstiprināt Visu Datu Dzēšanu?",
    
    msgDeleteConfirm: "Apstiprināt Dzēšanu",
    msgDeleteConfirmDetail: "Vai tiešām vēlaties dzēst '{questionText}'?",
    msgBulkDeleteConfirm: "Apstiprināt Vairāku Dzēšanu",
    msgBulkDeleteConfirmDetail: "Vai tiešām vēlaties dzēst {count} atlasītos jautājumus?",
    msgDeletedSuccess: "Veiksmīgi Dzēsts",
    msgDeletedSuccessDetail: "Atlasītais elements ir veiksmīgi dzēsts.",
    msgNoItemsSelected: "Lūdzu, atlasiet vismaz vienu elementu, ko dzēst.",

    confirmDeleteTestProfileTitle: "Apstiprināt Testa Dzēšanu",
    confirmDeleteTestProfileText: "Vai tiešām vēlaties dzēst testu '{name}' un visus tā jautājumus?",
    testProfileNameRequired: "Testa nosaukums ir obligāts.",
    testProfileDeleted: "Tests veiksmīgi dzēsts.",
    saveTestProfile: "Saglabāt Testu",
    createTestProfileTitle: "Izveidot Jaunu Testu",
    editTestProfileTitle: "Rediģēt Testa Detaļas",

    msgQuestionNotFoundEdit: "Rediģējamais jautājums netika atrasts. Iespējams, tas tika dzēsts.",
    
    msgAttention: "Uzmanību!",
    msgPleaseEnterAnswer: "Lūdzu, ievadiet atbildi.",
    msgPleaseSelectAnswer: "Lūdzu, izvēlieties atbildi.",
    msgPleaseAnswerLast: "Lūdzu, atbildiet uz pēdējo jautājumu pirms iesniegšanas.",
    timerMustBePositive: "Ja taimeris ir ieslēgts, tā ilgumam jābūt lielākam par 0.",
    timerNotEnabled: "Nav aktīvs",
    timeMinutesSeconds: "{minutes} min {seconds} sek",


    dataSource: "Datu avots",
    dataSourceBrowserMemory: "Pārlūka atmiņa",

    // Games
    gamesHubTitle: "Spēļu Centrs",
    navBackToGamesHub: "Atpakaļ uz Spēlēm",

    // Wordle LV Game
    wordleLvGameTitle: "Wordle (LV)",
    wordleLvGameDesc: "Uzmini 5 burtu vārdu latviešu valodā. Tev ir 6 mēģinājumi!",
    wordleAttemptsLeft: "Atlikušie mēģinājumi: {count}",
    wordleInvalidWordLength: "Vārdam jābūt {length} burtus garam.",
    wordleNotInWordList: "Šāda vārda nav sarakstā.",
    wordleWinMessage: "Apsveicu! Tu uzminēji vārdu: {word}",
    wordleLossMessage: "Diemžēl neizdevās. Pareizais vārds bija: {word}",
    wordlePlayAgain: "Spēlēt Vēlreiz",
    wordleKeyboardEnter: "Ievadīt",
    wordleKeyboardBackspace: "Dzēst",
    wordleNewGame: "Jauna Spēle",
    wordleHint: "Pačukstēt",
    wordleHintUsedOrUnavailable: "Mājiņa jau izmantota vai nav pieejama.",

    // Number Cruncher Game
    numberCruncherGameTitle: "Ātrais Rēķins",
    numberCruncherGameDesc: "Pārbaudi savas matemātikas prasmes, risinot uzdevumus laikā!",
    ncSelectDifficulty: "Izvēlies Grūtības Pakāpi:",
    ncDifficultyEasy: "Viegla",
    ncDifficultyMedium: "Vidēja",
    ncDifficultyHard: "Grūta",
    ncSelectMode: "Izvēlies Režīmu:",
    ncModeAdd: "Tikai Saskaitīšana",
    ncModeSubtract: "Tikai Atņemšana",
    ncModeMultiply: "Tikai Reizināšana",
    ncModeDivide: "Tikai Dalīšana",
    ncModeMixed: "Jaukts (Visi Veidi)",
    ncStartGame: "Sākt Spēli!",
    ncScore: "Punkti: {score}",
    ncTimeLeft: "Laiks: {time}s",
    ncEnterAnswer: "Ievadi atbildi...",
    ncSubmitAnswer: "Iesniegt",
    ncCorrect: "Pareizi!",
    ncIncorrect: "Nepareizi.",
    ncGameOver: "Spēle Beigusies!",
    ncFinalScore: "Tavs gala rezultāts: {score} punkti",
    
    // Flashcards
    flashcardDecksListTitle: "Zibatmiņu Kartīšu Komplekti",
    flashcardCreateNewDeck: "Izveidot Jaunu Komplektu",
    flashcardNoDecks: "Vēl nav izveidots neviens kartīšu komplekts.",
    flashcardDeckCardsCount: "Kartītes: {count}",
    flashcardDeckOpenHub: "Atvērt Komplektu",
    flashcardDeckEditDetails: "Rediģēt Detaļas",
    flashcardDeckDelete: "Dzēst Komplektu",
    flashcardDeckNameLabel: "Komplekta Nosaukums",
    flashcardDeckDescLabel: "Apraksts (nav obligāts)",
    flashcardSaveDeck: "Saglabāt Komplektu",
    flashcardDeckNameRequired: "Komplekta nosaukums ir obligāts.",
    flashcardDeckSaved: "Komplekts saglabāts!",
    flashcardDeckDeleted: "Komplekts dzēsts.",
    flashcardConfirmDeleteDeckTitle: "Apstiprināt Komplekta Dzēšanu",
    flashcardConfirmDeleteDeckText: "Vai tiešām vēlaties dzēst komplektu '{name}' un visas tā kartītes?",
    navBackToDecks: "Atpakaļ pie Komplektiem",

    flashcardDeckHubTitle: "Komplekts: {name}",
    flashcardDeckStartStudying: "Sākt Mācīties",
    flashcardDeckAddCard: "Pievienot Kartīti",
    flashcardDeckManageCards: "Pārvaldīt Kartītes",
    flashcardDeckNoCards: "Šajā komplektā vēl nav kartīšu.",
    flashcardEditCard: "Rediģēt",
    flashcardDeleteCard: "Dzēst",
    flashcardConfirmDeleteCardTitle: "Apstiprināt Kartītes Dzēšanu",
    flashcardConfirmDeleteCardText: "Vai tiešām vēlaties dzēst šo kartīti?",
    flashcardCardDeleted: "Kartīte dzēsta.",

    flashcardCreateEditCardTitleAdd: "Pievienot Jaunu Kartīti",
    flashcardCreateEditCardTitleEdit: "Rediģēt Kartīti",
    flashcardFrontTextLabel: "Priekšpuse (Jautājums/Vārds)",
    flashcardFrontImageLabel: "Priekšpuses Attēls (neobligāts)",
    flashcardBackTextLabel: "Aizmugure (Atbilde/Tulkojums)",
    flashcardBackImageLabel: "Aizmugures Attēls (neobligāts)",
    flashcardSaveCard: "Saglabāt Kartīti",
    flashcardCardFrontTextRequired: "Kartītes priekšpuses teksts ir obligāts.",
    flashcardCardSaved: "Kartīte saglabāta!",
    altPreview: "Priekšskatījums",

    flashcardStudyModeTitle: "Mācīšanās Režīms: {name}",
    flashcardCardXofY: "Kartīte {current} no {total}",
    flashcardFront: "Priekšpuse",
    flashcardBack: "Aizmugure",
    flashcardFlipCard: "Apgriezt",
    flashcardPreviousCard: "Iepriekšējā",
    flashcardNextCard: "Nākamā",
    flashcardStudyEnd: "Beigt Mācīšanos",
    flashcardShuffleCards: "Jaukt Kartītes",

    // Articles
    navArticles: "Raksti",
    articlesListTitle: "Rakstu Saraksts",
    articleFilterByCategory: "Filtrēt pēc Kategorijas",
    articleAllCategories: "Visas Kategorijas",
    articleNoArticles: "Pašlaik nav pieejamu rakstu.",
    articleReadStatus: "Statuss: {status}",
    statusRead: "Izlasīts",
    statusUnread: "Nav lasīts",
    articleMarkAsRead: "Atzīmēt kā Izlasītu",
    articlePublishedOn: "Publicēts: {date}",
    articleAuthor: "Autors: {author}",
    articleRead: "Lasīt Rakstu",
    navBackToArticles: "Atpakaļ pie Rakstiem",
    articleNoContentPlaceholder: "Raksta saturs nav pieejams.",
    articleNoExcerptFallback: "Nav pieejams īss apraksts.",
    
    // General
    msgError: "Kļūda",
    totalQuestions: "Kopā jautājumu:",
    altQuestionImage: "Jautājuma attēls",
    altOptionImage: "Atbildes varianta attēls",
    numberingNumbers: "Cipari (1, 2, 3...)",
    numberingLettersUpper: "Lielie burti (A, B, C...)",
    numberingLettersLower: "Mazie burti (a, b, c...)",
    numberingNone: "Bez numerācijas",
    navBackToHome: "Back Home",
    export: "Export",
    import: "Import",
    msgImportXlsxCsvConfirm: "Confirm XLSX/CSV Import",
    msgImportXlsxCsvConfirmDetail: "Are you sure you want to import questions from '{filename}' for test '{testName}'? Existing questions will be replaced.",
    msgXlsxImportedSuccessDetail: "{count} questions from '{filename}' successfully imported for test '{testName}'.",
    msgErrorMcqNeedsMinOptions: "Multiple choice question needs at least {minCount} options. Found: {foundCount}.",
  },
  [Language.EN]: {
    appTitle: "Learn.lv",
    navHome: "Home",
    navMyTests: "My Tests",
    navQuestionBank: "Question Bank",
    navCreateQuestion: "Create Question",
    navSettingsGeneral: "General Settings",
    navSettingsTest: "Test Settings",
    navStats: "Statistics",
    navImportExport: "Import/Export",
    navImportXlsxCsv: "Import (XLSX/CSV)",

    // Home page
    homeWelcome: "Welcome to Learn.lv!",
    homeModulesTitle: "Available Modules",
    homeInteractiveTestsTitle: "Interactive Tests",
    homeInteractiveTestsDesc: "Create and take custom tests to check your knowledge in various fields.",
    homeFlashcardsTitle: "Flashcards",
    homeFlashcardsDesc: "Create and study with flashcards. Great for learning new words and facts.",
    homeGamesTitle: "Games",
    homeGamesDesc: "Have fun and learn with interactive games.",
    homeArticlesTitle: "Educational Articles",
    homeArticlesDesc: "Read articles on various topics to expand your knowledge.",
    homeComingSoon: "Coming Soon!",

    // My Tests View
    myTestsTitle: "My Prepared Tests",
    myTestsCreateNew: "Create New Test",
    myTestsNoProfiles: "No tests created yet. Start by creating a new one!",
    myTestsProfileNameLabel: "Test name",
    myTestsProfileDescLabel: "Description (optional)",
    myTestsProfileQuestions: "Questions:",
    myTestsProfileCreated: "Created:",
    myTestsProfileUpdated: "Updated:",
    myTestsOpenHub: "Open Hub",
    myTestsEditDetails: "Edit Details",
    myTestsDelete: "Delete Test",

    // Test Profile Hub View
    testProfileHubTitle: "Test Hub: {name}",
    testHubStartTest: "Start Test",
    testHubManageBank: "Manage Questions",
    testHubAddQuestion: "Add New Question",
    testHubViewStats: "View Statistics",
    testHubConfigure: "Configure This Test",
    testHubBackToAllTests: "Back to All Tests",
    navBackToHub: "Back to Hub",

    // Quiz View
    quizNoQuestionsAvailable: "No questions available for test '{name}'.",
    quizNoQuestionsAdvice: "Please add some questions in the question bank or check test settings.",
    quizQuestionOf: "{current} of {total}",
    quizResultsTitle: "Results",
    quizYourScore: "Your score: {score} out of {totalPossible} ({percentage}%)",
    quizCorrectAnswerWas: "Correct answer: {correctAnswer}",
    quizYourAnswerWas: "Your answer: {userAnswer}. Correct: {correctAnswer}",
    quizAnswerNotAnswered: "You didn't answer. Correct answer: {correctAnswer}",
    quizPreviousBtn: "Previous",
    quizNextBtn: "Next",
    quizSubmitBtn: "Submit",
    quizTryAgainBtn: "Try Again",
    quizGoToAddFromEmpty: "Add Questions",
    quizGoToSettingsFromEmpty: "Test Settings",
    quizTimeRemaining: "Time remaining: {time}",
    quizTimeUpTitle: "Time's Up!",
    quizTimeUpMessage: "Your test was submitted automatically because time ran out.",

    // Question Bank View
    qBankTitle: "Question Bank: {name}",
    qBankSearchByText: "Search by text",
    qBankSearchPlaceholder: "Enter keyword...",
    qBankFilterByTopic: "Filter by topic",
    qBankAllTopics: "All topics",
    qBankTotalItems: "Total found: {count}",
    qBankSelectAll: "Select All Visible",
    qBankDeleteSelected: "Delete Selected",
    qBankItemsSelected: "Selected: {count}",
    qBankTypeLabel: "Type:",
    qBankAnswersCount: "Answers:",
    qBankCorrectIs: "Correct:",
    qBankEditBtn: "Edit",
    qBankDeleteBtn: "Delete",
    qBankNoQuestions: "No questions in this test ('{name}'). Add some!",
    qBankBackToQuestionBank: "Back to Question Bank",
    qBankQuestionImageIndicator: "Q. Image",
    qBankOptionImageIndicator: "Opt. Image",
    qBankIdIs: "ID:",
    qBankNotSpecified: "Not specified",
    qBankMappingTypeTip: "'multiple-choice', 'true-false', or 'fill-in-the-blank'. Defaults to 'multiple-choice'.",
    qBankMappingCorrectAnswerTip: "E.g., 'A', 'True', or 'Paris'. True/False can also be 'true'/'false'.",


    // Create/Edit Question View
    formTitleAdd: "Add New Question",
    formTitleEdit: "Edit Question",
    formQuestionTypeLabel: "Question type",
    formQuestionTextLabel: "Question text",
    formTopicLabel: "Topic (optional)",
    formTopicPlaceholder: "E.g., History, Mathematics",
    formQuestionImageLabel: "Question image (optional, up to {maxSize}KB)",
    formOptionsLabel: "Answer options",
    optionVariant: "Option",
    formAddOptionBtn: "Add option",
    formCorrectOptionLabel: "Correct option",
    formCorrectAnswerLabel: "Correct answer",
    formFillCorrectAnswerPlaceholder: "Enter the correct answer",
    formCancelBtn: "Cancel",
    formSaveQuestionBtn: "Save Question",
    formSaveChangesBtn: "Save Changes",
    formStatusSaving: "Saving...",
    formStatusSaved: "Question saved!",
    formStatusChangesSaved: "Changes saved!",
    optionImageLabel: "Option image (optional)",
    optionEmptyOrImage: "(empty or image only)",
    formImageWarning: "Images are stored in the browser. Large images (over {maxSize}KB) may slow down performance or not save.",

    // Question Types
    qTypeMultipleChoice: "Multiple Choice",
    qTypeTrueFalse: "True/False",
    qTypeFillInBlank: "Fill in the Blank",

    // Options (True/False)
    optionTrue: "True",
    optionFalse: "False",

    // Stats View
    statsTitle: "Statistics: {name}",
    statsTotalTests: "Total Tests",
    statsAverageScore: "Average Score",
    statsBestScore: "Best Score",
    statsHistoryTitle: "History",
    statsClearHistoryBtn: "Clear History",
    statsClearHistoryConfirm: "Are you sure you want to delete all history for test '{name}'?",
    statsClearHistoryConfirmDetail: "This action cannot be undone.",
    statsHistoryCleared: "History Cleared",
    statsHistoryClearedDetail: "History for test '{name}' has been successfully cleared.",
    statsNoHistory: "No history records for test '{name}'.",
    statsTestOn: "Test taken on:",
    statsScore: "Score:",
    statsTimeTaken: "Time taken:",

    // Settings View (Test Specific)
    testSettingsTitle: "Configuration: {name}",
    settingsAnswerNumbering: "Answer numbering style:",
    settingsNumQuestions: "Number of questions in test:",
    settingsAllQuestions: "All",
    settingsRandomQuestions: "Randomize questions",
    settingsRandomAnswers: "Randomize answers",
    settingsSaveBtn: "Save Settings",
    settingsEnableTimer: "Enable timer",
    settingsTimerDurationMinutes: "Timer duration (minutes):",

    // Settings View (General)
    generalSettingsTitle: "General Settings",
    settingsLanguageTitle: "Language",
    settingsDarkMode: "Dark mode",
    settingsDataManagement: "Data Management",
    settingsClearDataBtn: "Clear All Data",
    settingsClearDataWarning: "WARNING: This action will permanently delete ALL your saved tests, questions, history, and settings. Are you sure?",

    // Modals & Messages
    modalOK: "OK",
    modalCancel: "Cancel",
    modalConfirm: "Confirm",
    modalNotificationTitle: "Notification",
    modalErrorTitle: "Error",
    modalMappingTitle: "Data Mapping for Import",
    modalMappingDescription: "Please map your file's columns to the app's question fields. Optional fields can be left unmapped.",
    mapDetectedHeaders: "Detected Headers in File:",
    mapToFieldLabel: "Map to App Field '{fieldName}'",
    mapDoNotImport: "-- Do Not Import --",
    mapPreviewData: "First {count} rows from your file:",
    btnStartImport: "Start Import",


    msgValidationError: "Validation Error",
    msgErrorQuestionTextMissing: "Question text is required.",
    msgNeedAtLeastTwoOptions: "Multiple choice question needs at least 2 options.",
    msgChooseCorrectAnswer: "Please choose the correct answer.",
    msgMustEnterFillInAnswer: "Please enter the correct answer for the blank.",
    msgErrorCorrectAnswerMismatchMcq: "The specified correct answer ('{correctAnswer}') does not match any of the provided options: {optionList}.",
    msgErrorInvalidCorrectAnswerTf: "The correct answer for True/False must be '{trueText}' or '{falseText}'. You provided: '{providedAnswer}'.",
    msgErrorCorrectAnswerMissingMcq: "Please provide the correct answer for the multiple-choice question.",
    msgErrorCorrectAnswerMissingFib: "Please provide the correct answer for the fill-in-the-blank question.",
    msgOptionIsImageOnlyCorrect: "An option that is image-only cannot be the correct answer without accompanying text.",
    
    msgFileTooLarge: "File Too Large",
    msgFileTooLargeDetail: "Maximum allowed file size is {maxSize}KB. Your file: {fileSize}KB.",
    msgMaxOptionsReached: "Maximum Options Reached",
    msgMaxOptionsDetail: "You can add a maximum of {max} answer options.",

    msgImportConfirm: "Confirm Import",
    msgImportConfirmDetail: "Are you sure you want to import questions from '{filename}' for test '{testName}'? Existing questions will be replaced.",
    msgImportedSuccess: "Successfully Imported",
    msgImportedSuccessDetail: "Questions for test '{testName}' have been successfully imported.",
    msgXlsxImportedSuccess: "{count} questions from '{filename}' successfully imported for test '{testName}'.",
    msgImportError: "Import Error",
    msgImportErrorInvalidFormat: "Invalid file format or structure.",
    msgImportErrorReadFile: "Failed to read file. Error: {errorMessage}",
    msgImportErrorReadingFile: "Failed to read file.",
    msgXlsxImportErrorNoSheet: "No sheets found in the XLSX file.",
    msgXlsxImportErrorNoHeaders: "No headers found in the selected sheet.",
    msgXlsxImportErrorMapping: "Question text field ('Question text') must be mapped for import.",
    msgXlsxImportNoValidQuestionsFound: "No valid questions found in the file, or all had errors.",
    msgXlsxImportCompletedWithRowErrorsTitle: "Import Completed with Row Errors",
    msgXlsxImportCompletedWithRowErrorsDetail: "Some rows could not be imported. Total {errorCount} erroneous rows. First {shownErrorCount} shown:\n{errorListString}",
    msgXlsxImportRowErrorPrefix: "Row {rowNum}",
    msgErrorUnexpectedRowProcessing: "Unexpected error processing row: {errorMessage}",
    msgErrorMoreErrorsText: "more errors...",

    msgExported: "Successfully Exported",
    msgExportedDetail: "Questions from test '{testName}' saved to file '{filename}'.",
    msgNoDataToExport: "No Data to Export",
    msgNoDataToExportDetail: "Test '{testName}' has no questions to export.",
    
    msgSettingsSaved: "Settings Saved",
    msgSettingsSavedDetail: "Changes have been successfully saved.",
    msgSavingErrorDetail: "Error saving. Check data and try again.",
    
    msgDataCleared: "All Data Cleared",
    msgDataClearedDetail: "All your data has been successfully cleared from browser storage.",
    msgClearAllDataConfirm: "Confirm Clear All Data?",
    
    msgDeleteConfirm: "Confirm Deletion",
    msgDeleteConfirmDetail: "Are you sure you want to delete '{questionText}'?",
    msgBulkDeleteConfirm: "Confirm Bulk Deletion",
    msgBulkDeleteConfirmDetail: "Are you sure you want to delete {count} selected questions?",
    msgDeletedSuccess: "Successfully Deleted",
    msgDeletedSuccessDetail: "The selected item has been successfully deleted.",
    msgNoItemsSelected: "Please select at least one item to delete.",

    confirmDeleteTestProfileTitle: "Confirm Test Deletion",
    confirmDeleteTestProfileText: "Are you sure you want to delete test '{name}' and all its questions?",
    testProfileNameRequired: "Test name is required.",
    testProfileDeleted: "Test successfully deleted.",
    saveTestProfile: "Save Test",
    createTestProfileTitle: "Create New Test",
    editTestProfileTitle: "Edit Test Details",

    msgQuestionNotFoundEdit: "Question to edit not found. It might have been deleted.",

    msgAttention: "Attention!",
    msgPleaseEnterAnswer: "Please enter an answer.",
    msgPleaseSelectAnswer: "Please select an answer.",
    msgPleaseAnswerLast: "Please answer the last question before submitting.",
    timerMustBePositive: "If timer is enabled, its duration must be greater than 0.",
    timerNotEnabled: "Not active",
    timeMinutesSeconds: "{minutes} min {seconds} sec",

    dataSource: "Data source",
    dataSourceBrowserMemory: "Browser memory",

    // Games
    gamesHubTitle: "Games Hub",
    navBackToGamesHub: "Back to Games",

    // Wordle LV Game
    wordleLvGameTitle: "Wordle (LV)",
    wordleLvGameDesc: "Guess the 5-letter Latvian word. You have 6 attempts!",
    wordleAttemptsLeft: "Attempts left: {count}",
    wordleInvalidWordLength: "Word must be {length} letters long.",
    wordleNotInWordList: "Word not in list.",
    wordleWinMessage: "Congratulations! You guessed the word: {word}",
    wordleLossMessage: "Unfortunately, you didn't guess. The word was: {word}",
    wordlePlayAgain: "Play Again",
    wordleKeyboardEnter: "Enter",
    wordleKeyboardBackspace: "Backspace",
    wordleNewGame: "New Game",
    wordleHint: "Hint",
    wordleHintUsedOrUnavailable: "Hint already used or unavailable.",

    // Number Cruncher Game
    numberCruncherGameTitle: "Number Cruncher",
    numberCruncherGameDesc: "Test your math skills by solving problems against the clock!",
    ncSelectDifficulty: "Select Difficulty:",
    ncDifficultyEasy: "Easy",
    ncDifficultyMedium: "Medium",
    ncDifficultyHard: "Hard",
    ncSelectMode: "Select Mode:",
    ncModeAdd: "Addition Only",
    ncModeSubtract: "Subtraction Only",
    ncModeMultiply: "Multiplication Only",
    ncModeDivide: "Division Only",
    ncModeMixed: "Mixed (All Types)",
    ncStartGame: "Start Game!",
    ncScore: "Score: {score}",
    ncTimeLeft: "Time: {time}s",
    ncEnterAnswer: "Enter answer...",
    ncSubmitAnswer: "Submit",
    ncCorrect: "Correct!",
    ncIncorrect: "Incorrect.",
    ncGameOver: "Game Over!",
    ncFinalScore: "Your final score: {score} points",

    // Flashcards
    flashcardDecksListTitle: "Flashcard Decks",
    flashcardCreateNewDeck: "Create New Deck",
    flashcardNoDecks: "No flashcard decks created yet.",
    flashcardDeckCardsCount: "Cards: {count}",
    flashcardDeckOpenHub: "Open Deck",
    flashcardDeckEditDetails: "Edit Details",
    flashcardDeckDelete: "Delete Deck",
    flashcardDeckNameLabel: "Deck Name",
    flashcardDeckDescLabel: "Description (optional)",
    flashcardSaveDeck: "Save Deck",
    flashcardDeckNameRequired: "Deck name is required.",
    flashcardDeckSaved: "Deck saved!",
    flashcardDeckDeleted: "Deck deleted.",
    flashcardConfirmDeleteDeckTitle: "Confirm Deck Deletion",
    flashcardConfirmDeleteDeckText: "Are you sure you want to delete the deck '{name}' and all its cards?",
    navBackToDecks: "Back to Decks",

    flashcardDeckHubTitle: "Deck: {name}",
    flashcardDeckStartStudying: "Start Studying",
    flashcardDeckAddCard: "Add Card",
    flashcardDeckManageCards: "Manage Cards",
    flashcardDeckNoCards: "No cards in this deck yet.",
    flashcardEditCard: "Edit",
    flashcardDeleteCard: "Delete",
    flashcardConfirmDeleteCardTitle: "Confirm Card Deletion",
    flashcardConfirmDeleteCardText: "Are you sure you want to delete this card?",
    flashcardCardDeleted: "Card deleted.",

    flashcardCreateEditCardTitleAdd: "Add New Card",
    flashcardCreateEditCardTitleEdit: "Edit Card",
    flashcardFrontTextLabel: "Front (Question/Word)",
    flashcardFrontImageLabel: "Front Image (optional)",
    flashcardBackTextLabel: "Back (Answer/Translation)",
    flashcardBackImageLabel: "Back Image (optional)",
    flashcardSaveCard: "Save Card",
    flashcardCardFrontTextRequired: "Card front text is required.",
    flashcardCardSaved: "Card saved!",
    altPreview: "Preview",

    flashcardStudyModeTitle: "Study Mode: {name}",
    flashcardCardXofY: "Card {current} of {total}",
    flashcardFront: "Front",
    flashcardBack: "Back",
    flashcardFlipCard: "Flip",
    flashcardPreviousCard: "Previous",
    flashcardNextCard: "Next",
    flashcardStudyEnd: "End Study",
    flashcardShuffleCards: "Shuffle Cards",

    // Articles
    navArticles: "Articles",
    articlesListTitle: "Articles List",
    articleFilterByCategory: "Filter by Category",
    articleAllCategories: "All Categories",
    articleNoArticles: "No articles available at the moment.",
    articleReadStatus: "Status: {status}",
    statusRead: "Read",
    statusUnread: "Unread",
    articleMarkAsRead: "Mark as Read",
    articlePublishedOn: "Published on: {date}",
    articleAuthor: "Author: {author}",
    articleRead: "Read Article",
    navBackToArticles: "Back to Articles",
    articleNoContentPlaceholder: "Article content is not available.",
    articleNoExcerptFallback: "No excerpt available.",
    
    // General
    msgError: "Error",
    totalQuestions: "Total questions:",
    altQuestionImage: "Question image",
    altOptionImage: "Option image",
    numberingNumbers: "Numbers (1, 2, 3...)",
    numberingLettersUpper: "Uppercase Letters (A, B, C...)",
    numberingLettersLower: "Lowercase Letters (a, b, c...)",
    numberingNone: "No numbering",
    navBackToHome: "Back Home",
    export: "Export",
    import: "Import",
    msgImportXlsxCsvConfirm: "Confirm XLSX/CSV Import",
    msgImportXlsxCsvConfirmDetail: "Are you sure you want to import questions from '{filename}' for test '{testName}'? Existing questions will be replaced.",
    msgXlsxImportedSuccessDetail: "{count} questions from '{filename}' successfully imported for test '{testName}'.",
    msgErrorMcqNeedsMinOptions: "Multiple choice question needs at least {minCount} options. Found: {foundCount}.",
  },
  [Language.UK]: {
    appTitle: "Вчись.lv",
    navHome: "Головна",
    navMyTests: "Мої Тести",
    navQuestionBank: "Банк Запитань",
    navCreateQuestion: "Створити Запитання",
    navSettingsGeneral: "Загальні Налаштування",
    navSettingsTest: "Налаштування Тесту",
    navStats: "Статистика",
    navImportExport: "Імпорт/Експорт",
    navImportXlsxCsv: "Імпорт (XLSX/CSV)",
    
    homeWelcome: "Ласкаво просимо до Вчись.lv!",
    homeModulesTitle: "Доступні Модулі",
    homeInteractiveTestsTitle: "Інтерактивні Тести",
    homeInteractiveTestsDesc: "Створюйте та проходьте власні тести, щоб перевірити свої знання в різних галузях.",
    homeFlashcardsTitle: "Флеш-картки",
    homeFlashcardsDesc: "Створюйте та вивчайте за допомогою карток. Чудово підходить для вивчення нових слів та фактів.",
    homeGamesTitle: "Ігри",
    homeGamesDesc: "Розважайся та навчайся з інтерактивними іграми.",
    homeArticlesTitle: "Освітні Статті",
    homeArticlesDesc: "Читайте статті на різноманітні теми, щоб розширити свої знання.",
    homeComingSoon: "Незабаром!",

    myTestsTitle: "Мої Підготовлені Тести",
    myTestsCreateNew: "Створити Новий Тест",
    myTestsNoProfiles: "Ще не створено жодного тесту. Почніть зі створення нового!",
    myTestsProfileNameLabel: "Назва тесту",
    myTestsProfileDescLabel: "Опис (необов'язково)",
    myTestsProfileQuestions: "Запитання:",
    myTestsProfileCreated: "Створено:",
    myTestsProfileUpdated: "Оновлено:",
    myTestsOpenHub: "Відкрити Центр",
    myTestsEditDetails: "Редагувати Деталі",
    myTestsDelete: "Видалити Тест",

    testProfileHubTitle: "Центр Тесту: {name}",
    testHubStartTest: "Почати Тест",
    testHubManageBank: "Керувати Запитаннями",
    testHubAddQuestion: "Додати Нове Запитання",
    testHubViewStats: "Переглянути Статистику",
    testHubConfigure: "Налаштувати Цей Тест",
    testHubBackToAllTests: "Назад до Всіх Тестів",
    navBackToHub: "Назад до Центру",
    
    quizNoQuestionsAvailable: "Для тесту '{name}' немає доступних запитань.",
    quizNoQuestionsAdvice: "Будь ласка, додайте запитання до банку запитань або перевірте налаштування тесту.",
    quizQuestionOf: "{current} з {total}",
    quizResultsTitle: "Результати",
    quizYourScore: "Ваш результат: {score} з {totalPossible} ({percentage}%)",
    quizCorrectAnswerWas: "Правильна відповідь: {correctAnswer}",
    quizYourAnswerWas: "Ваша відповідь: {userAnswer}. Правильна: {correctAnswer}",
    quizAnswerNotAnswered: "Ви не відповіли. Правильна відповідь: {correctAnswer}",
    quizPreviousBtn: "Попереднє",
    quizNextBtn: "Наступне",
    quizSubmitBtn: "Надіслати",
    quizTryAgainBtn: "Спробувати Ще",
    quizGoToAddFromEmpty: "Додати Запитання",
    quizGoToSettingsFromEmpty: "Налаштування Тесту",
    quizTimeRemaining: "Залишилося часу: {time}",
    quizTimeUpTitle: "Час Вийшов!",
    quizTimeUpMessage: "Ваш тест було автоматично надіслано, оскільки час закінчився.",
    
    qBankTitle: "Банк Запитань: {name}",
    qBankSearchByText: "Пошук за текстом",
    qBankSearchPlaceholder: "Введіть ключове слово...",
    qBankFilterByTopic: "Фільтрувати за темою",
    qBankAllTopics: "Всі теми",
    qBankTotalItems: "Всього знайдено: {count}",
    qBankSelectAll: "Вибрати Всі Показані",
    qBankDeleteSelected: "Видалити Вибрані",
    qBankItemsSelected: "Вибрано: {count}",
    qBankTypeLabel: "Тип:",
    qBankAnswersCount: "Відповіді:",
    qBankCorrectIs: "Правильна:",
    qBankEditBtn: "Редагувати",
    qBankDeleteBtn: "Видалити",
    qBankNoQuestions: "У цьому тесті ('{name}') немає запитань. Додайте!",
    qBankBackToQuestionBank: "Назад до Банку Запитань",
    qBankQuestionImageIndicator: "Зобр. пит.",
    qBankOptionImageIndicator: "Зобр. відп.",
    qBankIdIs: "ID:",
    qBankNotSpecified: "Не вказано",
    qBankMappingTypeTip: "'multiple-choice', 'true-false', або 'fill-in-the-blank'. За замовчуванням 'multiple-choice'.",
    qBankMappingCorrectAnswerTip: "Напр., 'A', 'True', або 'Київ'. True/False також може бути 'так'/'ні'.",
    
    formTitleAdd: "Додати Нове Запитання",
    formTitleEdit: "Редагувати Запитання",
    formQuestionTypeLabel: "Тип запитання",
    formQuestionTextLabel: "Текст запитання",
    formTopicLabel: "Тема (необов'язково)",
    formTopicPlaceholder: "Напр., Історія, Математика",
    formQuestionImageLabel: "Зображення до запитання (необов'язково, до {maxSize}KB)",
    formOptionsLabel: "Варіанти відповіді",
    optionVariant: "Варіант",
    formAddOptionBtn: "Додати варіант",
    formCorrectOptionLabel: "Правильний варіант",
    formCorrectAnswerLabel: "Правильна відповідь",
    formFillCorrectAnswerPlaceholder: "Введіть правильну відповідь",
    formCancelBtn: "Скасувати",
    formSaveQuestionBtn: "Зберегти Запитання",
    formSaveChangesBtn: "Зберегти Зміни",
    formStatusSaving: "Збереження...",
    formStatusSaved: "Запитання збережено!",
    formStatusChangesSaved: "Зміни збережено!",
    optionImageLabel: "Зображення варіанту (необов'язково)",
    optionEmptyOrImage: "(порожньо або тільки зображення)",
    formImageWarning: "Зображення зберігаються у браузері. Великі зображення (понад {maxSize}KB) можуть сповільнити роботу або не зберегтися.",

    qTypeMultipleChoice: "Множинний Вибір",
    qTypeTrueFalse: "Так/Ні",
    qTypeFillInBlank: "Заповнити Пропуск",

    optionTrue: "Так",
    optionFalse: "Ні",

    statsTitle: "Статистика: {name}",
    statsTotalTests: "Всього Тестів",
    statsAverageScore: "Середній Результат",
    statsBestScore: "Найкращий Результат",
    statsHistoryTitle: "Історія",
    statsClearHistoryBtn: "Очистити Історію",
    statsClearHistoryConfirm: "Ви дійсно бажаєте видалити всю історію для тесту '{name}'?",
    statsClearHistoryConfirmDetail: "Цю дію неможливо буде скасувати.",
    statsHistoryCleared: "Історію Очищено",
    statsHistoryClearedDetail: "Історію для тесту '{name}' успішно очищено.",
    statsNoHistory: "Немає записів історії для тесту '{name}'.",
    statsTestOn: "Тест пройдено:",
    statsScore: "Результат:",
    statsTimeTaken: "Витрачений час:",

    testSettingsTitle: "Налаштування: {name}",
    settingsAnswerNumbering: "Стиль нумерації відповідей:",
    settingsNumQuestions: "Кількість запитань у тесті:",
    settingsAllQuestions: "Всі",
    settingsRandomQuestions: "Перемішувати запитання",
    settingsRandomAnswers: "Перемішувати відповіді",
    settingsSaveBtn: "Зберегти Налаштування",
    settingsEnableTimer: "Увімкнути таймер",
    settingsTimerDurationMinutes: "Тривалість таймера (хвилини):",

    generalSettingsTitle: "Загальні Налаштування",
    settingsLanguageTitle: "Мова",
    settingsDarkMode: "Темний режим",
    settingsDataManagement: "Керування Даними",
    settingsClearDataBtn: "Видалити Всі Дані",
    settingsClearDataWarning: "УВАГА: Ця дія НАЗАВЖДИ видалить ВСІ ваші збережені тести, запитання, історію та налаштування. Ви впевнені?",

    modalOK: "Гаразд",
    modalCancel: "Скасувати",
    modalConfirm: "Підтвердити",
    modalNotificationTitle: "Повідомлення",
    modalErrorTitle: "Помилка",
    modalMappingTitle: "Зіставлення Даних для Імпорту",
    modalMappingDescription: "Будь ласка, зіставте стовпці вашого файлу з полями запитань програми. Необов'язкові поля можна залишити незіставленими.",
    mapDetectedHeaders: "Виявлені Заголовки у Файлі:",
    mapToFieldLabel: "Зіставити з Полем Програми '{fieldName}'",
    mapDoNotImport: "-- Не імпортувати --",
    mapPreviewData: "Перші {count} рядків з вашого файлу:",
    btnStartImport: "Почати Імпорт",

    msgValidationError: "Помилка Валідації",
    msgErrorQuestionTextMissing: "Текст запитання є обов'язковим.",
    msgNeedAtLeastTwoOptions: "Для запитання з множинним вибором потрібно щонайменше 2 варіанти.",
    msgChooseCorrectAnswer: "Будь ласка, виберіть правильну відповідь.",
    msgMustEnterFillInAnswer: "Будь ласка, введіть правильну відповідь для пропуску.",
    msgErrorCorrectAnswerMismatchMcq: "Вказана правильна відповідь ('{correctAnswer}') не збігається з жодним із наданих варіантів: {optionList}.",
    msgErrorInvalidCorrectAnswerTf: "Правильна відповідь для Так/Ні має бути '{trueText}' або '{falseText}'. Ви вказали: '{providedAnswer}'.",
    msgErrorCorrectAnswerMissingMcq: "Будь ласка, надайте правильну відповідь для запитання з множинним вибором.",
    msgErrorCorrectAnswerMissingFib: "Будь ласка, надайте правильну відповідь для запитання на заповнення пропуску.",
    msgOptionIsImageOnlyCorrect: "Варіант, що містить лише зображення, не може бути правильною відповіддю без супровідного тексту.",
    
    msgFileTooLarge: "Файл Занадто Великий",
    msgFileTooLargeDetail: "Максимально дозволений розмір файлу - {maxSize}KB. Ваш файл: {fileSize}KB.",
    msgMaxOptionsReached: "Досягнуто Максимальної Кількість Варіантів",
    msgMaxOptionsDetail: "Ви можете додати щонайбільше {max} варіантів відповіді.",
    
    msgImportConfirm: "Підтвердити Імпорт",
    msgImportConfirmDetail: "Ви дійсно бажаєте імпортувати запитання з '{filename}' для тесту '{testName}'? Існуючі запитання буде замінено.",
    msgImportedSuccess: "Успішно Імпортовано",
    msgImportedSuccessDetail: "Запитання для тесту '{testName}' успішно імпортовано.",
    msgXlsxImportedSuccess: "{count} запитань з '{filename}' успішно імпортовано для тесту '{testName}'.",
    msgImportError: "Помилка Імпорту",
    msgImportErrorInvalidFormat: "Недійсний формат або структура файлу.",
    msgImportErrorReadFile: "Не вдалося прочитати файл. Помилка: {errorMessage}",
    msgImportErrorReadingFile: "Не вдалося прочитати файл.",
    msgXlsxImportErrorNoSheet: "У файлі XLSX не знайдено жодного аркуша.",
    msgXlsxImportErrorNoHeaders: "У вибраному аркуші не знайдено заголовків стовпців.",
    msgXlsxImportErrorMapping: "Поле тексту запитання ('Текст запитання') має бути зіставлене для імпорту.",
    msgXlsxImportNoValidQuestionsFound: "У файлі не знайдено жодного дійсного запитання, або всі містили помилки.",
    msgXlsxImportCompletedWithRowErrorsTitle: "Імпорт Завершено з Помилками в Рядках",
    msgXlsxImportCompletedWithRowErrorsDetail: "Деякі рядки не вдалося імпортувати. Всього {errorCount} помилкових рядків. Показано перші {shownErrorCount}:\n{errorListString}",
    msgXlsxImportRowErrorPrefix: "Рядок {rowNum}",
    msgErrorUnexpectedRowProcessing: "Неочікувана помилка обробки рядка: {errorMessage}",
    msgErrorMoreErrorsText: "додаткових помилок...",

    msgExported: "Успішно Експортовано",
    msgExportedDetail: "Запитання з тесту '{testName}' збережено у файл '{filename}'.",
    msgNoDataToExport: "Немає Даних для Експорту",
    msgNoDataToExportDetail: "Тест '{testName}' не містить запитань для експорту.",
    
    msgSettingsSaved: "Налаштування Збережено",
    msgSettingsSavedDetail: "Зміни успішно збережено.",
    msgSavingErrorDetail: "Помилка збереження. Перевірте дані та спробуйте ще раз.",
    
    msgDataCleared: "Всі Дані Видалено",
    msgDataClearedDetail: "Всі ваші дані успішно видалено зі сховища браузера.",
    msgClearAllDataConfirm: "Підтвердити Видалення Всіх Даних?",
    
    msgDeleteConfirm: "Підтвердити Видалення",
    msgDeleteConfirmDetail: "Ви дійсно бажаєте видалити '{questionText}'?",
    msgBulkDeleteConfirm: "Підтвердити Масове Видалення",
    msgBulkDeleteConfirmDetail: "Ви дійсно бажаєте видалити {count} вибраних запитань?",
    msgDeletedSuccess: "Успішно Видалено",
    msgDeletedSuccessDetail: "Вибраний елемент успішно видалено.",
    msgNoItemsSelected: "Будь ласка, виберіть хоча б один елемент для видалення.",
    
    confirmDeleteTestProfileTitle: "Підтвердити Видалення Тесту",
    confirmDeleteTestProfileText: "Ви дійсно бажаєте видалити тест '{name}' та всі його запитання?",
    testProfileNameRequired: "Назва тесту є обов'язковою.",
    testProfileDeleted: "Тест успішно видалено.",
    saveTestProfile: "Зберегти Тест",
    createTestProfileTitle: "Створити Новий Тест",
    editTestProfileTitle: "Редагувати Деталі Тесту",
    
    msgQuestionNotFoundEdit: "Запитання для редагування не знайдено. Можливо, його було видалено.",
    
    msgAttention: "Увага!",
    msgPleaseEnterAnswer: "Будь ласка, введіть відповідь.",
    msgPleaseSelectAnswer: "Будь ласка, виберіть відповідь.",
    msgPleaseAnswerLast: "Будь ласка, дайте відповідь на останнє запитання перед надсиланням.",
    timerMustBePositive: "Якщо таймер увімкнено, його тривалість має бути більшою за 0.",
    timerNotEnabled: "Не активний",
    timeMinutesSeconds: "{minutes} хв {seconds} сек",

    dataSource: "Джерело даних",
    dataSourceBrowserMemory: "Пам'ять браузера",

    // Games
    gamesHubTitle: "Ігровий Центр",
    navBackToGamesHub: "Назад до Ігор",

    // Wordle LV Game
    wordleLvGameTitle: "Wordle (LV)",
    wordleLvGameDesc: "Відгадай 5-буквене латиське слово. У тебе 6 спроб!",
    wordleAttemptsLeft: "Залишилося спроб: {count}",
    wordleInvalidWordLength: "Слово має містити {length} літер.",
    wordleNotInWordList: "Такого слова немає у списку.",
    wordleWinMessage: "Вітаю! Ти відгадав слово: {word}",
    wordleLossMessage: "На жаль, не вдалося. Правильне слово було: {word}",
    wordlePlayAgain: "Грати Ще",
    wordleKeyboardEnter: "Ввести",
    wordleKeyboardBackspace: "Стерти",
    wordleNewGame: "Нова Гра",
    wordleHint: "Підказка",
    wordleHintUsedOrUnavailable: "Підказку вже використано або вона недоступна.",

    // Number Cruncher Game
    numberCruncherGameTitle: "Швидкий Рахунок",
    numberCruncherGameDesc: "Перевір свої математичні навички, розв'язуючи приклади на час!",
    ncSelectDifficulty: "Обери Складність:",
    ncDifficultyEasy: "Легка",
    ncDifficultyMedium: "Середня",
    ncDifficultyHard: "Складна",
    ncSelectMode: "Обери Режим:",
    ncModeAdd: "Тільки Додавання",
    ncModeSubtract: "Тільки Віднімання",
    ncModeMultiply: "Тільки Множення",
    ncModeDivide: "Тільки Ділення",
    ncModeMixed: "Змішаний (Всі Типи)",
    ncStartGame: "Почати Гру!",
    ncScore: "Рахунок: {score}",
    ncTimeLeft: "Час: {time}с",
    ncEnterAnswer: "Введи відповідь...",
    ncSubmitAnswer: "Надіслати",
    ncCorrect: "Правильно!",
    ncIncorrect: "Неправильно.",
    ncGameOver: "Гра Закінчена!",
    ncFinalScore: "Твій кінцевий рахунок: {score} очок",
    
    // Flashcards
    flashcardDecksListTitle: "Колоди Флеш-карток",
    flashcardCreateNewDeck: "Створити Нову Колоду",
    flashcardNoDecks: "Ще не створено жодної колоди карток.",
    flashcardDeckCardsCount: "Карток: {count}",
    flashcardDeckOpenHub: "Відкрити Колоду",
    flashcardDeckEditDetails: "Редагувати Деталі",
    flashcardDeckDelete: "Видалити Колоду",
    flashcardDeckNameLabel: "Назва Колоди",
    flashcardDeckDescLabel: "Опис (необов'язково)",
    flashcardSaveDeck: "Зберегти Колоду",
    flashcardDeckNameRequired: "Назва колоди є обов'язковою.",
    flashcardDeckSaved: "Колоду збережено!",
    flashcardDeckDeleted: "Колоду видалено.",
    flashcardConfirmDeleteDeckTitle: "Підтвердити Видалення Колоди",
    flashcardConfirmDeleteDeckText: "Ви дійсно бажаєте видалити колоду '{name}' та всі її картки?",
    navBackToDecks: "Назад до Колод",
    
    flashcardDeckHubTitle: "Колода: {name}",
    flashcardDeckStartStudying: "Почати Вивчення",
    flashcardDeckAddCard: "Додати Картку",
    flashcardDeckManageCards: "Керувати Картками",
    flashcardDeckNoCards: "У цій колоді ще немає карток.",
    flashcardEditCard: "Редагувати",
    flashcardDeleteCard: "Видалити",
    flashcardConfirmDeleteCardTitle: "Підтвердити Видалення Картки",
    flashcardConfirmDeleteCardText: "Ви дійсно бажаєте видалити цю картку?",
    flashcardCardDeleted: "Картку видалено.",
    
    flashcardCreateEditCardTitleAdd: "Додати Нову Картку",
    flashcardCreateEditCardTitleEdit: "Редагувати Картку",
    flashcardFrontTextLabel: "Лицьова сторона (Питання/Слово)",
    flashcardFrontImageLabel: "Зображення Лицьової (необов'язково)",
    flashcardBackTextLabel: "Зворотна сторона (Відповідь/Переклад)",
    flashcardBackImageLabel: "Зображення Зворотної (необов'язково)",
    flashcardSaveCard: "Зберегти Картку",
    flashcardCardFrontTextRequired: "Текст лицьової сторони картки є обов'язковим.",
    flashcardCardSaved: "Картку збережено!",
    altPreview: "Попередній перегляд",
    
    flashcardStudyModeTitle: "Режим Вивчення: {name}",
    flashcardCardXofY: "Картка {current} з {total}",
    flashcardFront: "Лицьова",
    flashcardBack: "Зворотна",
    flashcardFlipCard: "Перевернути",
    flashcardPreviousCard: "Попередня",
    flashcardNextCard: "Наступна",
    flashcardStudyEnd: "Завершити Вивчення",
    flashcardShuffleCards: "Перемішати Картки",

    // Articles
    navArticles: "Статті",
    articlesListTitle: "Список Статей",
    articleFilterByCategory: "Фільтрувати за Категорією",
    articleAllCategories: "Всі Категорії",
    articleNoArticles: "На даний момент статті відсутні.",
    articleReadStatus: "Статус: {status}",
    statusRead: "Прочитано",
    statusUnread: "Не прочитано",
    articleMarkAsRead: "Відзначити як Прочитане",
    articlePublishedOn: "Опубліковано: {date}",
    articleAuthor: "Автор: {author}",
    articleRead: "Читати Статтю",
    navBackToArticles: "Назад до Статей",
    articleNoContentPlaceholder: "Зміст статті недоступний.",
    articleNoExcerptFallback: "Короткий опис відсутній.",
        
    // General
    msgError: "Помилка",
    totalQuestions: "Всього запитань:",
    altQuestionImage: "Зображення запитання",
    altOptionImage: "Зображення варіанту відповіді",
    numberingNumbers: "Цифри (1, 2, 3...)",
    numberingLettersUpper: "Великі літери (A, B, C...)",
    numberingLettersLower: "Малі літери (a, b, c...)",
    numberingNone: "Без нумерації",
    navBackToHome: "Назад на Головну",
    export: "Експорт",
    import: "Імпорт",
    msgImportXlsxCsvConfirm: "Підтвердити Імпорт XLSX/CSV",
    msgImportXlsxCsvConfirmDetail: "Ви дійсно бажаєте імпортувати запитання з '{filename}' для тесту '{testName}'? Існуючі запитання буде замінено.",
    msgXlsxImportedSuccessDetail: "{count} запитань з '{filename}' успішно імпортовано для тесту '{testName}'.",
    msgErrorMcqNeedsMinOptions: "Для запитання з множинним вибором потрібно щонайменше {minCount} варіанти. Знайдено: {foundCount}.",
  }
};
